[package]
name = "zookeeper-client-sync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.29"
once_cell = "1.18.0"
thiserror = "1.0.50"
tokio = "1.33.0"
zookeeper-client = "0.6.1"
